#!/bin/bash

# Use dmenu to select a directory
search_directory="/home/pavle/Books"

# Collect ebook files (PDF, EPUB, MOBI, DJVU) in the selected directory
ebook_files=$(find "$search_directory" -type f \( -iname "*.pdf" -o -iname "*.epub" -o -iname "*.mobi" -o -iname "*.djvu" \))

# Check if there are any ebook files
if [ -z "$ebook_files" ]; then
    echo "No ebook files found in the selected directory."
    exit 1
fi


# Trim the directory part of the path, showing only the file name relative to the selected directory
file_names=$(echo "$ebook_files" | sed "s|^$search_directory/||")


# Use dmenu to select an ebook file
selected_file_name=$(echo "$file_names" | dmenu -i -p "Select an ebook:" -l 46)

# If a file was selected, find the full path of the selected file and open it in zathura
 if [ -n "$selected_file_name" ]; then
     selected_file="$search_directory/$selected_file_name"
     zathura "$selected_file" &
else
     echo "No file selected."
 fi
